(()=>{
'use strict';
const stage=document.getElementById('creative-stage'),create=document.getElementById('create-variants'),state=document.getElementById('creative-state');
let expanded=false;
function setExpanded(value){expanded=value;stage.classList.toggle('expanded',value);create.setAttribute('aria-expanded',String(value));create.innerHTML=value?'Back to master <span>↶</span>':'Create variants <span>↗</span>';state.textContent=value?'Three formats. One consistent product.':'One master, ready to adapt.';}
create?.addEventListener('click',()=>setExpanded(!expanded));
const words={en:['A fresh<br>perspective.','Your daily<br>reset.','Made for<br>every day.'],ar:['بداية<br>منعشة.','انتعاشك<br>اليومي.','لكلّ<br>يوم.']};
document.querySelectorAll('[data-language]').forEach(button=>button.addEventListener('click',()=>{const lang=button.dataset.language;document.querySelectorAll('[data-language]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelectorAll('.ad-copy').forEach((el,i)=>{el.innerHTML=words[lang][i];el.lang=lang;el.dir=lang==='ar'?'rtl':'ltr';});if(!expanded)setExpanded(true);state.textContent=lang==='ar'?'Arabic copy. The same product and brand asset.':'English copy. The same product and brand asset.';}));
const route=[['IN PARALLEL / STUDIO','Win the people making the work.','Steer Media makes AI ad films for Dettol and Finish. Approach the studio with a real production brief: demonstrate how one approved creative becomes consistent, localized variants. Start this conversation alongside direct outreach to Reckitt.','Arshmaan Ali Khuwaja · Creative Director, Steer Media'],['IN PARALLEL / BRAND','Win the people owning the outcome.','Reckitt Middle East is building an AI content engine in Dubai. Approach Haseeb directly, in parallel with the studio: understand the brief, agree what success looks like, and demonstrate a production pipeline for the brand’s teams and agencies.','Haseeb Kamal Siddiqui · Regional Marketing Director, Reckitt Middle East'],['THEN / SCALE','Prove it locally. Scale what works.','Once a real brief demonstrates value, use the evidence to propose expansion across brands and markets. Reckitt’s job ad describes variants for KSA, UAE and the GCC, followed by taking the framework to other markets.','Ishaan Kaul · Product Line for AI in Creative Tech, Reckitt']];
document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.route),d=route[i];document.querySelector('.route-map').dataset.progress=String(i);document.querySelectorAll('[data-route]').forEach(node=>{node.classList.toggle('selected',node===b);node.setAttribute('aria-pressed',String(node===b));});['route-step','route-title','route-copy','route-person'].forEach((id,k)=>document.getElementById(id).textContent=d[k]);}));
const cards=Array.from(document.querySelectorAll('.model-card')),videos=cards.map(c=>c.querySelector('video'));
const play=document.getElementById('play-pair'),strike=document.getElementById('strike-moments'),time=document.getElementById('lab-time'),timeLabel=document.getElementById('lab-time-label'),message=document.getElementById('lab-message'),speed=document.getElementById('lab-speed');
let synchronized=false,frame=0,startToken=0;
const selected=()=>cards.filter(c=>c.querySelector('input').checked).map(c=>c.querySelector('video'));
function paintTime(t){time.value=String(t);timeLabel.textContent=t.toFixed(2)+' / 8 s';}
function stop(){synchronized=false;startToken++;cancelAnimationFrame(frame);videos.forEach(v=>v.pause());play.innerHTML='Play selected pair <span>▶</span>';}
function seek(video,t){if(video.readyState>=1)video.currentTime=t;else{video.addEventListener('loadedmetadata',()=>video.currentTime=t,{once:true});video.load();}}
function updateSelection(){stop();const count=selected().length;cards.forEach(c=>c.classList.toggle('selected',c.querySelector('input').checked));play.disabled=count!==2;message.textContent=count===2?'Two selected. Play together, scrub, or inspect the strike moments.':'Select exactly two cards ('+count+' selected).';}
cards.forEach(c=>c.querySelector('input').addEventListener('change',updateSelection));
function follow(){if(!synchronized)return;const pair=selected();if(pair.length!==2){stop();return;}if(pair.some(v=>v.ended)){paintTime(8);stop();return;}const [lead,other]=pair;if(lead.paused){stop();return;}if(Math.abs(lead.currentTime-other.currentTime)>.12&&other.readyState>=2)other.currentTime=lead.currentTime;paintTime(lead.currentTime);frame=requestAnimationFrame(follow);}
play.addEventListener('click',async()=>{if(synchronized){stop();return;}stop();const pair=selected();if(pair.length!==2)return;const token=++startToken;const t=Number(time.value)>=7.95?0:Number(time.value);pair.forEach(v=>{seek(v,t);v.playbackRate=Number(speed.value);});try{await Promise.all(pair.map(v=>v.play()));if(token!==startToken){pair.forEach(v=>v.pause());return;}synchronized=true;play.innerHTML='Pause comparison <span>Ⅱ</span>';message.textContent='Playing the selected pair on a shared timeline.';follow();}catch{stop();message.textContent='Playback could not start. Use the controls on each video.';}});
time.addEventListener('input',()=>{stop();selected().forEach(v=>seek(v,Number(time.value)));paintTime(Number(time.value));message.textContent='Selected videos paused at the same timestamp.';});
speed.addEventListener('change',()=>videos.forEach(v=>v.playbackRate=Number(speed.value)));
strike.addEventListener('click',()=>{stop();cards.forEach(c=>seek(c.querySelector('video'),Number(c.dataset.strike)));message.textContent='Individual review times: Seedance 4.30 s · Gen-4.5 3.32 s · Kling 5.12 s · Veo 4.90 s. Press a video’s play control to inspect the surrounding action.';time.value=0;timeLabel.textContent='Per clip';});
cards.forEach(c=>{const video=c.querySelector('video');c.addEventListener('pointerenter',e=>{if(e.pointerType!=='mouse'||synchronized||matchMedia('(prefers-reduced-motion: reduce)').matches)return;videos.filter(v=>v!==video).forEach(v=>v.pause());video.playbackRate=Number(speed.value);video.play().catch(()=>{});});c.addEventListener('pointerleave',()=>{if(!synchronized)video.pause();});video.addEventListener('error',()=>{message.textContent='A video could not load. Reopen this page using the local preview link.';});});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting&&!synchronized)entry.target.pause();}),{threshold:.05});videos.forEach(v=>observer.observe(v)); const labObserver=new IntersectionObserver(entries=>{if(entries[0]&&!entries[0].isIntersecting)stop();},{threshold:0});labObserver.observe(document.getElementById('model-lab'));
window.addEventListener('hashchange',()=>{if(!['#models','#model-lab'].includes(location.hash))stop();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
})();
